spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/pr2s
    username: sa
    password:
    driver-class-name: org.h2.Driver
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
  resources:
    static-locations: file:src/main/resources/static/
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: gkdlshtjdrb@gmail.com
    password: vjzyutgplgeuyzif
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

storage:
  rootLocation: files